/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xsearch_amazon;

import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
   
        TestCases tests = new TestCases(); 

        tests.testcase01();
        tests.testcase02();
        tests.testcase03();

        tests.endTest(); 
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
